language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-head
  - rbx-2

install: gem install net-ssh test-unit mocha

script: rake test

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
